### ISSUE TITLE
Can't install due to vs code version incompatibility (version 1.47.3)

### ISSUE THREAD

**Issue by lukestanbra** [damonsk/vscode-wardley-maps#2]
Tried to install and got the following:

```Unable to install 'damonsk.vscode-wardley-maps' extension because it is not compatible with the current version of VS Code (version 1.47.3).```

Is there a list of compatible versions somewhere?

**Comment by damonsk** [comment]
It requires version 1.5 (September 2020 Update) https://code.visualstudio.com/updates/v1_50

Are you unable to update? if so I can look into earlier version support.
