### ISSUE TITLE
Latest release from OMW to vscode plugin

### ISSUE THREAD

**Issue by Preskton** [damonsk/vscode-wardley-maps#21]
The current release of plugin's `wmlandscape` is `1.268.1`, which is very old:

```bash
cat node_modules/wmlandscape/package.json | grep version
	"version": "1.268.1",
```

What would it take to pick up the version currently published on https://onlinewardleymaps.com/?

/cc https://github.com/damonsk/vscode-wardley-maps/pull/23

**Comment by damonsk** [comment]
Hi @Preskton 

The following file needs updating to include recent pipeline work from OWM. https://github.com/damonsk/onlinewardleymaps/blob/master/frontend/wmlandscape/src/index.js

The following will also need some work:

Update the language file: https://github.com/damonsk/vscode-wardley-maps/blob/master/syntaxes/wardleymap.tmLanguage.json

Include new snippets: https://github.com/damonsk/vscode-wardley-maps/blob/master/snippets/snippets.code-snippets

It's on my todo list however if you'd like to contribute a PR would be great.

**Comment by Preskton** [comment]
Great, happy to try to contrib. I'll poke around and assemble a list of questions. :)

One that comes to mind immediately - is it safe to assume the `Iterations` function depends on AWS Amplify and wouldn't be something that would end up in the vscode plugin?

**Comment by damonsk** [comment]
Wouldn't want amplify to be pulled in, which file has the dependency?

**Comment by Preskton** [comment]
> Wouldn't want amplify to be pulled in, which file has the dependency?

I don't think it needs to be pulled in as part of hosting `wmlandscape`. A different way to phrase my question -- and I think I know the answer -- is the "iterations" feature part of `wmlandscape`? And I'm pretty sure the answer is "no".

**Comment by Preskton** [comment]
After upgrading dependencies in #23, I didn't end up having to pull in amplify.

**Comment by damonsk** [comment]
PR merged and published to marketplace.  https://marketplace.visualstudio.com/items?itemName=damonsk.vscode-wardley-maps

**Comment by Preskton** [comment]
Looks great, thanks for fixing up those dangling dependencies! :)
