### ISSUE TITLE
Display an existing map shows empty canvas

### ISSUE THREAD

**Issue by demeringo** [damonsk/vscode-wardley-maps#26]
# Bug description:
Opening an existing map file display an empty canvas and may lead to erasing file content.

Possibly linked to #24 ?

# How to reproduce:

1. Linux 
2. Close any existing _Map view_ tab
3. Open an existing owm file in vs code (_without_  having the map view previously opened, this is important to reproduce).
4. Command "Wardley map: Display map" => an empty canvas is displayed
5. Add a component in GUI mode (clicking inside the display view): the existing content of the file is replaced by this new component (only) 
6. Subsequent edit work fine.

# Workaround:
The bug does not manifest if the display map view was already active/open for a different file (before loading the owm file).

Or if _I click inside the text file while presented with the empty canvas_ (this refreshes the view with file content  and subsequent edits wok fine).

# Other:
A sincere thank you for the great work so far on this much appreciated extension 🙏

**Comment by damonsk** [comment]
Thanks @demeringo - fix will be live shortly.
