### ISSUE TITLE
Co-publish in Open VSX

### ISSUE THREAD

**Issue by yujikiriki** [damonsk/vscode-wardley-maps#3]
Open VSX is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions. See this [article](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php) for more information.

It would be cool if this marvellous extension is available in OpenVSX.

the guide to publish it can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

There is a [Github Action](https://github.com/HaaLeo/publish-vscode-extension#readme) to publish the extension to OpenVSX that can be used too.

**Comment by damonsk** [comment]
Thanks to @johannrichard  - https://open-vsx.org/extension/damonsk/vscode-wardley-maps

**Comment by johannrichard** [comment]
> Thanks to @johannrichard  - https://open-vsx.org/extension/damonsk/vscode-wardley-maps 

You're most welcome. Thanks for building this extension.

**Comment by johannrichard** [comment]
VSCodium already picked it up and updated to the version on Open-VSX. Am obviously the first one to download from Open-VSX. Hopefully not the last! 😁

![image](https://user-images.githubusercontent.com/189003/99886950-ba4bf000-2c40-11eb-800c-ea74fd413c29.png)
